# Generated by Django 5.2.6 on 2025-09-13 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_product_is_featured_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
